name: Security Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflows:
    workflows: ["Bandit CWE Pipeline"]
    types:
      - completed

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install bandit requests colorama

      - name: Run Bandit Security Analysis
        run: |
          bandit -r ./ > bandit_report_with_cwe.json || true
          cat bandit_report_with_cwe.json

      - name: Run Security Score Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 scripts/analyze_score.py

      - name: Generate Security Badge
        run: python3 scripts/generate_security_badge.py

      - name: Commit and Push Security Badge
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add badges/security.svg
          git commit -m 'Atualizando badge de segurança'
          git push
        continue-on-error: true

      - name: Upload Security Report
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: security_report.md

    - name: Adjust File Permissions
      run: chmod -R 777 scripts/
    
    - name: Ensure security_tests directory exists
      run: mkdir -p security_tests

    - name: Run Bandit on Multiple Repositories
      run: scripts/run_bandit_multiple.sh

    - name: Show Generate Reports
      run: ls -R security_tests/

    - name: Upload All Security Reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: security_tests/*.json
