name: Bandit CWE Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bandit-analysis:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        run: bandit -r ./ --severity-level high > bandit_report.json || true

      - name: Add CWE Codes
        run: python3 add_cwe_to_bandit.py

      - name: Save Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report-with-cwe
          path: bandit_report_with_cwe.json
